<a href="https://colab.research.google.com/github/Meanz12/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_6%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 6강 - 데이터 전처리 1

In [16]:
import requests

## params
api_key = "6a4e5366496d656135315452646c4a"
api_type = 'json'
api_service = 'energyUseDataSummaryInfo'
api_startIndex = 1
api_endIndex = 5

## needed info
needed_columns = ['YEAR', 'MON', 'MM_TYPE', 'EUS', 'GUS', 'WUS', 'HUS']

## function
def get_year_months():
    year_months = []
    for year in range(2015, 2024+1):
        for month in range(1,12+1):
            year_months.append(f'{year}{month:02d}')
    return year_months

year_months = get_year_months()
results = []

for ym in get_year_months():
    year = ym[:4]
    month = ym[4:]
    url = f"http://openapi.seoul.go.kr:8088/{api_key}/{api_type}/{api_service}/{api_startIndex}/{api_endIndex}/{year}/{month}"
    response = requests.get(url, timeout=3)

    if response.status_code == 200:
        #print("api 호출 성공")
        data = response.json()
        rows = data[api_service]['row']
        filtered_rows = []

        for row in rows:
            if row['MM_TYPE'] == "개인":
                new_row = {}
                for col in needed_columns:
                    new_row[col] = row[col]
                filtered_rows.append(new_row)
        results.extend(filtered_rows)
    else :
        print(f"{year}{month}: {response.status_code} 오류")

print(results)

[{'YEAR': '2015', 'MON': '01', 'MM_TYPE': '개인', 'EUS': '193784708', 'GUS': '59133720', 'WUS': '12819757.886', 'HUS': '22740838.937'}, {'YEAR': '2015', 'MON': '02', 'MM_TYPE': '개인', 'EUS': '189974230', 'GUS': '56487358', 'WUS': '12656888.218', 'HUS': '18793320.213'}, {'YEAR': '2015', 'MON': '05', 'MM_TYPE': '개인', 'EUS': '177289769', 'GUS': '22060892', 'WUS': '13086734.214', 'HUS': '1320895.801'}, {'YEAR': '2015', 'MON': '06', 'MM_TYPE': '개인', 'EUS': '186073153', 'GUS': '12677645', 'WUS': '14241651.402', 'HUS': '294312.634'}, {'YEAR': '2015', 'MON': '07', 'MM_TYPE': '개인', 'EUS': '165114568', 'GUS': '8893640', 'WUS': '12083879.038', 'HUS': '702863.645'}, {'YEAR': '2015', 'MON': '08', 'MM_TYPE': '개인', 'EUS': '242000479', 'GUS': '7619018', 'WUS': '15164553.742', 'HUS': '460288.965'}, {'YEAR': '2015', 'MON': '10', 'MM_TYPE': '개인', 'EUS': '186473958', 'GUS': '8924018', 'WUS': '14711828.766', 'HUS': '3167520.127'}, {'YEAR': '2015', 'MON': '12', 'MM_TYPE': '개인', 'EUS': '203388142', 'GUS': '40095231', 'WUS': '13904162.958', 'HUS': '21102616.717'}, {'YEAR': '2016', 'MON': '01', 'MM_TYPE': '개인', 'EUS': '215330620', 'GUS': '57641741', 'WUS': '13218916.436', 'HUS': '27186166.133'}, {'YEAR': '2016', 'MON': '02', 'MM_TYPE': '개인', 'EUS': '216677664', 'GUS': '68879796', 'WUS': '13312113.622', 'HUS': '21452994.715'}, {'YEAR': '2016', 'MON': '03', 'MM_TYPE': '개인', 'EUS': '203451798', 'GUS': '60019600', 'WUS': '13191615.499', 'HUS': '14070182.978'}, {'YEAR': '2016', 'MON': '04', 'MM_TYPE': '개인', 'EUS': '202541336', 'GUS': '40370608', 'WUS': '13748935.736', 'HUS': '4556396.936'}, {'YEAR': '2016', 'MON': '05', 'MM_TYPE': '개인', 'EUS': '195448592', 'GUS': '23077064', 'WUS': '13762618.524', 'HUS': '1166907.615'}, {'YEAR': '2016', 'MON': '06', 'MM_TYPE': '개인', 'EUS': '205061790', 'GUS': '13344932', 'WUS': '14543461.284', 'HUS': '340601.066'}, {'YEAR': '2016', 'MON': '09', 'MM_TYPE': '개인', 'EUS': '241676328', 'GUS': '7030657', 'WUS': '15233262.266', 'HUS': '2597269.386'}, {'YEAR': '2016', 'MON': '10', 'MM_TYPE': '개인', 'EUS': '197827666', 'GUS': '10129547', 'WUS': '15173666.268', 'HUS': '2142328.405'}, {'YEAR': '2016', 'MON': '11', 'MM_TYPE': '개인', 'EUS': '204812090', 'GUS': '23915383', 'WUS': '7215169', 'HUS': '10865402.481'}, {'YEAR': '2017', 'MON': '01', 'MM_TYPE': '개인', 'EUS': '222980440', 'GUS': '61781772', 'WUS': '14077034.016', 'HUS': '20567265.356'}, {'YEAR': '2017', 'MON': '02', 'MM_TYPE': '개인', 'EUS': '226181991', 'GUS': '73537514', 'WUS': '13724166.552', 'HUS': '17733782.246'}, {'YEAR': '2017', 'MON': '03', 'MM_TYPE': '개인', 'EUS': '208386870', 'GUS': '64297007', 'WUS': '13598081.92', 'HUS': '11477962.549'}, {'YEAR': '2017', 'MON': '05', 'MM_TYPE': '개인', 'EUS': '209894672', 'GUS': '25103152', 'WUS': '12950202.184', 'HUS': '19809726.81'}, {'YEAR': '2017', 'MON': '08', 'MM_TYPE': '개인', 'EUS': '297850172', 'GUS': '8429188', 'WUS': '14291829.084', 'HUS': '118927.011'}, {'YEAR': '2017', 'MON': '09', 'MM_TYPE': '개인', 'EUS': '232360099', 'GUS': '8981707', 'WUS': '13842675.562', 'HUS': '1279967.753'}, {'YEAR': '2017', 'MON': '10', 'MM_TYPE': '개인', 'EUS': '202205893', 'GUS': '11910453', 'WUS': '13811362.596', 'HUS': '2177857.689'}, {'YEAR': '2017', 'MON': '11', 'MM_TYPE': '개인', 'EUS': '215620132', 'GUS': '26041170', 'WUS': '13268391.686', 'HUS': '12290667.843'}, {'YEAR': '2018', 'MON': '02', 'MM_TYPE': '개인', 'EUS': '243271752', 'GUS': '88496947', 'WUS': '12905042.86', 'HUS': '22671708.494'}, {'YEAR': '2018', 'MON': '03', 'MM_TYPE': '개인', 'EUS': '219203768', 'GUS': '73426397', 'WUS': '12769174.532', 'HUS': '10924939.951'}, {'YEAR': '2018', 'MON': '06', 'MM_TYPE': '개인', 'EUS': '222820943', 'GUS': '17132065', 'WUS': '14051336.092', 'HUS': '285820.628'}, {'YEAR': '2018', 'MON': '07', 'MM_TYPE': '개인', 'EUS': '269705511', 'GUS': '11259835', 'WUS': '14333667.052', 'HUS': '25843523.832'}, {'YEAR': '2018', 'MON': '11', 'MM_TYPE': '개인', 'EUS': '227294230', 'GUS': '31239511', 'WUS': '13706690.088', 'HUS': '10276290.855'}, {'YEAR': '2018', 'MON': '12', 'MM_TYPE': '개인', 'EUS': '238692561', 'GUS': '54019855', 'WUS': '13732488.456', 'HUS': '20421845.603'}, {'YEAR': '2019', 'MON': '01', 'MM_TYPE': '개인', 'EUS': '253600219', 'GUS': '80308239', 'WUS': '13442971.1', 'HUS': '21963093.848'}, {'YEAR': '2019', 'MON': '02', 'MM_TYPE': '개인', 'EUS': '244927344', 'GUS': '81902188', 'WUS': '13495213.9', 'HUS': '106134923.132'}, {'YEAR': '2019', 'MON': '03', 'MM_TYPE': '개인', 'EUS': '223736787', 'GUS': '65146586.443', 'WUS': '13167550', 'HUS': '13194262.09'}, {'YEAR': '2019', 'MON': '04', 'MM_TYPE': '개인', 'EUS': '232166121', 'GUS': '49391508', 'WUS': '13753270.8', 'HUS': '7858587.747'}, {'YEAR': '2019', 'MON': '06', 'MM_TYPE': '개인', 'EUS': '226119779', 'GUS': '15771701', 'WUS': '14223536.4', 'HUS': '331690.945'}, {'YEAR': '2019', 'MON': '07', 'MM_TYPE': '개인', 'EUS': '257854441', 'GUS': '10700835', 'WUS': '14451345.9', 'HUS': '968957.161'}, {'YEAR': '2019', 'MON': '10', 'MM_TYPE': '개인', 'EUS': '228095713', 'GUS': '11876816', 'WUS': '14804362.3', 'HUS': '2590192.143'}, {'YEAR': '2019', 'MON': '11', 'MM_TYPE': '개인', 'EUS': '231283724', 'GUS': '24835894', 'WUS': '14123043.9', 'HUS': '14983364.884'}, {'YEAR': '2019', 'MON': '12', 'MM_TYPE': '개인', 'EUS': '244976724', 'GUS': '54509050', 'WUS': '14184785.2', 'HUS': '23558262.283'}, {'YEAR': '2020', 'MON': '02', 'MM_TYPE': '개인', 'EUS': '254879033', 'GUS': '76363768', 'WUS': '14052828.8', 'HUS': '20848668.612'}, {'YEAR': '2020', 'MON': '03', 'MM_TYPE': '개인', 'EUS': '244369714', 'GUS': '64367515', 'WUS': '13841531', 'HUS': '14194450.151'}, {'YEAR': '2020', 'MON': '04', 'MM_TYPE': '개인', 'EUS': '247831442', 'GUS': '48373693', 'WUS': '14618775.2', 'HUS': '8499792.566'}, {'YEAR': '2020', 'MON': '08', 'MM_TYPE': '개인', 'EUS': '320723239', 'GUS': '10177428', 'WUS': '15600097.8', 'HUS': '286814.663'}, {'YEAR': '2020', 'MON': '11', 'MM_TYPE': '개인', 'EUS': '247308528', 'GUS': '30095679', 'WUS': '14835013.9', 'HUS': '12882737.572'}, {'YEAR': '2020', 'MON': '12', 'MM_TYPE': '개인', 'EUS': '265370372', 'GUS': '51095720', 'WUS': '15036546.3', 'HUS': '26512966.052'}, {'YEAR': '2021', 'MON': '01', 'MM_TYPE': '개인', 'EUS': '287882528', 'GUS': '80955422', 'WUS': '14273105.8', 'HUS': '31069705.783'}, {'YEAR': '2021', 'MON': '02', 'MM_TYPE': '개인', 'EUS': '271224712', 'GUS': '85581769', 'WUS': '13679936.9', 'HUS': '22238103.26'}, {'YEAR': '2021', 'MON': '05', 'MM_TYPE': '개인', 'EUS': '241741576', 'GUS': '24638403', 'WUS': '14312460.916', 'HUS': '2246730.037'}, {'YEAR': '2021', 'MON': '06', 'MM_TYPE': '개인', 'EUS': '254958704', 'GUS': '18898880', 'WUS': '15174790.6', 'HUS': '396903.273'}, {'YEAR': '2021', 'MON': '07', 'MM_TYPE': '개인', 'EUS': '334733756', 'GUS': '9631171', 'WUS': '16619105.064', 'HUS': '5529269.058'}, {'YEAR': '2021', 'MON': '08', 'MM_TYPE': '개인', 'EUS': '409719040', 'GUS': '10205066', 'WUS': '15737994.8', 'HUS': '127607.838'}, {'YEAR': '2021', 'MON': '09', 'MM_TYPE': '개인', 'EUS': '290606638', 'GUS': '6602872', 'WUS': '15497783.9', 'HUS': '159066.058'}, {'YEAR': '2021', 'MON': '10', 'MM_TYPE': '개인', 'EUS': '253845816', 'GUS': '13840155', 'WUS': '15930639.8', 'HUS': '4220985.501'}, {'YEAR': '2021', 'MON': '11', 'MM_TYPE': '개인', 'EUS': '255516339', 'GUS': '28571168', 'WUS': '14975050.4', 'HUS': '13463697.643'}, {'YEAR': '2021', 'MON': '12', 'MM_TYPE': '개인', 'EUS': '265314948', 'GUS': '54651317', 'WUS': '14873728.5', 'HUS': '25989752.285'}, {'YEAR': '2022', 'MON': '03', 'MM_TYPE': '개인', 'EUS': '256771728', 'GUS': '75577723', 'WUS': '14181287.1', 'HUS': '15843818.715'}, {'YEAR': '2022', 'MON': '05', 'MM_TYPE': '개인', 'EUS': '238866649', 'GUS': '28185559', 'WUS': '14344240.1', 'HUS': '1457446.39'}, {'YEAR': '2022', 'MON': '06', 'MM_TYPE': '개인', 'EUS': '254486733', 'GUS': '15468022', 'WUS': '15087457.3', 'HUS': '838539.99'}, {'YEAR': '2022', 'MON': '07', 'MM_TYPE': '개인', 'EUS': '336383318', 'GUS': '10701998', 'WUS': '14907198', 'HUS': '50033.827'}, {'YEAR': '2022', 'MON': '08', 'MM_TYPE': '개인', 'EUS': '382965547', 'GUS': '8718677', 'WUS': '15555926.8', 'HUS': '3278812.728'}, {'YEAR': '2022', 'MON': '09', 'MM_TYPE': '개인', 'EUS': '294121752', 'GUS': '9220604.8', 'WUS': '15016541.4', 'HUS': '7221052.414'}, {'YEAR': '2022', 'MON': '11', 'MM_TYPE': '개인', 'EUS': '252081207', 'GUS': '28471902', 'WUS': '14485236.6', 'HUS': '10685943.786'}, {'YEAR': '2022', 'MON': '12', 'MM_TYPE': '개인', 'EUS': '266989892', 'GUS': '52230601', 'WUS': '14538742.5', 'HUS': '31655489.658'}, {'YEAR': '2023', 'MON': '04', 'MM_TYPE': '개인', 'EUS': '247142965', 'GUS': '38484227', 'WUS': '13951884.7', 'HUS': '4292056.162'}, {'YEAR': '2023', 'MON': '06', 'MM_TYPE': '개인', 'EUS': '259143276', 'GUS': '14742811', 'WUS': '14822130.1', 'HUS': '1169879.028'}, {'YEAR': '2023', 'MON': '08', 'MM_TYPE': '개인', 'EUS': '407479395', 'GUS': '8486915', 'WUS': '15402396.8', 'HUS': '530124.99'}, {'YEAR': '2023', 'MON': '09', 'MM_TYPE': '개인', 'EUS': '332452167', 'GUS': '7674573', 'WUS': '14941654.4', 'HUS': '19457189.828'}, {'YEAR': '2023', 'MON': '10', 'MM_TYPE': '개인', 'EUS': '255560826', 'GUS': '11273798', 'WUS': '14918622.9', 'HUS': '3049594.261'}, {'YEAR': '2023', 'MON': '11', 'MM_TYPE': '개인', 'EUS': '255362764', 'GUS': '23749738', 'WUS': '14439208.8', 'HUS': '13225464.736'}, {'YEAR': '2023', 'MON': '12', 'MM_TYPE': '개인', 'EUS': '271015225', 'GUS': '47560201', 'WUS': '14519931.6', 'HUS': '24169250.596'}, {'YEAR': '2024', 'MON': '01', 'MM_TYPE': '개인', 'EUS': '290223476', 'GUS': '65608930', 'WUS': '14119336.8', 'HUS': '26759601.094'}, {'YEAR': '2024', 'MON': '02', 'MM_TYPE': '개인', 'EUS': '280810330', 'GUS': '65184440', 'WUS': '14247296.7', 'HUS': '18696968.203'}, {'YEAR': '2024', 'MON': '03', 'MM_TYPE': '개인', 'EUS': '259332255', 'GUS': '58563376', 'WUS': '13792441.8', 'HUS': '13455710.256'}, {'YEAR': '2024', 'MON': '04', 'MM_TYPE': '개인', 'EUS': '256332884', 'GUS': '35786315', 'WUS': '14330249.1', 'HUS': '3099650.225'}, {'YEAR': '2024', 'MON': '05', 'MM_TYPE': '개인', 'EUS': '244740675', 'GUS': '18077028', 'WUS': '14158142.9', 'HUS': '28333197.76'}, {'YEAR': '2024', 'MON': '06', 'MM_TYPE': '개인', 'EUS': '270158916', 'GUS': '11903071', 'WUS': '14966075.6', 'HUS': '20226852.923'}, {'YEAR': '2024', 'MON': '07', 'MM_TYPE': '개인', 'EUS': '340000663', 'GUS': '8319412', 'WUS': '14992942.2', 'HUS': '2173041.617'}, {'YEAR': '2024', 'MON': '08', 'MM_TYPE': '개인', 'EUS': '463971328', 'GUS': '7072251', 'WUS': '15873544.6', 'HUS': '130082.263'}, {'YEAR': '2024', 'MON': '09', 'MM_TYPE': '개인', 'EUS': '409872908', 'GUS': '5729131', 'WUS': '15143321.6', 'HUS': '3420507.136'}, {'YEAR': '2024', 'MON': '10', 'MM_TYPE': '개인', 'EUS': '282268119', 'GUS': '8233421', 'WUS': '15297669.9', 'HUS': '2695491.396'}, {'YEAR': '2024', 'MON': '11', 'MM_TYPE': '개인', 'EUS': '257927956', 'GUS': '17418221', 'WUS': '14678672.5', 'HUS': '8836296.454'}, {'YEAR': '2024', 'MON': '12', 'MM_TYPE': '개인', 'EUS': '134828126', 'GUS': '42103424', 'WUS': '7326853.6', 'HUS': '1513199.277'}]

In [18]:
import pandas as pd

df = pd.DataFrame(results)
## DataFrame 인덱스 출력
print(df.index)
## DataFrame 컬럼 출력
print(df.columns)
## DataFrame 행 출력
print(df.values.tolist())
print(df.values) # python numpy
## DataFrame 값 출력
print(df.values.flatten())

RangeIndex(start=0, stop=83, step=1)
Index(['YEAR', 'MON', 'MM_TYPE', 'EUS', 'GUS', 'WUS', 'HUS'], dtype='object')
[['2015', '01', '개인', '193784708', '59133720', '12819757.886', '22740838.937'], ['2015', '02', '개인', '189974230', '56487358', '12656888.218', '18793320.213'], ['2015', '05', '개인', '177289769', '22060892', '13086734.214', '1320895.801'], ['2015', '06', '개인', '186073153', '12677645', '14241651.402', '294312.634'], ['2015', '07', '개인', '165114568', '8893640', '12083879.038', '702863.645'], ['2015', '08', '개인', '242000479', '7619018', '15164553.742', '460288.965'], ['2015', '10', '개인', '186473958', '8924018', '14711828.766', '3167520.127'], ['2015', '12', '개인', '203388142', '40095231', '13904162.958', '21102616.717'], ['2016', '01', '개인', '215330620', '57641741', '13218916.436', '27186166.133'], ['2016', '02', '개인', '216677664', '68879796', '13312113.622', '21452994.715'], ['2016', '03', '개인', '203451798', '60019600', '13191615.499', '14070182.978'], ['2016', '04', '개인', '202541336', '40370608', '13748935.736', '4556396.936'], ['2016', '05', '개인', '195448592', '23077064', '13762618.524', '1166907.615'], ['2016', '06', '개인', '205061790', '13344932', '14543461.284', '340601.066'], ['2016', '09', '개인', '241676328', '7030657', '15233262.266', '2597269.386'], ['2016', '10', '개인', '197827666', '10129547', '15173666.268', '2142328.405'], ['2016', '11', '개인', '204812090', '23915383', '7215169', '10865402.481'], ['2017', '01', '개인', '222980440', '61781772', '14077034.016', '20567265.356'], ['2017', '02', '개인', '226181991', '73537514', '13724166.552', '17733782.246'], ['2017', '03', '개인', '208386870', '64297007', '13598081.92', '11477962.549'], ['2017', '05', '개인', '209894672', '25103152', '12950202.184', '19809726.81'], ['2017', '08', '개인', '297850172', '8429188', '14291829.084', '118927.011'], ['2017', '09', '개인', '232360099', '8981707', '13842675.562', '1279967.753'], ['2017', '10', '개인', '202205893', '11910453', '13811362.596', '2177857.689'], ['2017', '11', '개인', '215620132', '26041170', '13268391.686', '12290667.843'], ['2018', '02', '개인', '243271752', '88496947', '12905042.86', '22671708.494'], ['2018', '03', '개인', '219203768', '73426397', '12769174.532', '10924939.951'], ['2018', '06', '개인', '222820943', '17132065', '14051336.092', '285820.628'], ['2018', '07', '개인', '269705511', '11259835', '14333667.052', '25843523.832'], ['2018', '11', '개인', '227294230', '31239511', '13706690.088', '10276290.855'], ['2018', '12', '개인', '238692561', '54019855', '13732488.456', '20421845.603'], ['2019', '01', '개인', '253600219', '80308239', '13442971.1', '21963093.848'], ['2019', '02', '개인', '244927344', '81902188', '13495213.9', '106134923.132'], ['2019', '03', '개인', '223736787', '65146586.443', '13167550', '13194262.09'], ['2019', '04', '개인', '232166121', '49391508', '13753270.8', '7858587.747'], ['2019', '06', '개인', '226119779', '15771701', '14223536.4', '331690.945'], ['2019', '07', '개인', '257854441', '10700835', '14451345.9', '968957.161'], ['2019', '10', '개인', '228095713', '11876816', '14804362.3', '2590192.143'], ['2019', '11', '개인', '231283724', '24835894', '14123043.9', '14983364.884'], ['2019', '12', '개인', '244976724', '54509050', '14184785.2', '23558262.283'], ['2020', '02', '개인', '254879033', '76363768', '14052828.8', '20848668.612'], ['2020', '03', '개인', '244369714', '64367515', '13841531', '14194450.151'], ['2020', '04', '개인', '247831442', '48373693', '14618775.2', '8499792.566'], ['2020', '08', '개인', '320723239', '10177428', '15600097.8', '286814.663'], ['2020', '11', '개인', '247308528', '30095679', '14835013.9', '12882737.572'], ['2020', '12', '개인', '265370372', '51095720', '15036546.3', '26512966.052'], ['2021', '01', '개인', '287882528', '80955422', '14273105.8', '31069705.783'], ['2021', '02', '개인', '271224712', '85581769', '13679936.9', '22238103.26'], ['2021', '05', '개인', '241741576', '24638403', '14312460.916', '2246730.037'], ['2021', '06', '개인', '254958704', '18898880', '15174790.6', '396903.273'], ['2021', '07', '개인', '334733756', '9631171', '16619105.064', '5529269.058'], ['2021', '08', '개인', '409719040', '10205066', '15737994.8', '127607.838'], ['2021', '09', '개인', '290606638', '6602872', '15497783.9', '159066.058'], ['2021', '10', '개인', '253845816', '13840155', '15930639.8', '4220985.501'], ['2021', '11', '개인', '255516339', '28571168', '14975050.4', '13463697.643'], ['2021', '12', '개인', '265314948', '54651317', '14873728.5', '25989752.285'], ['2022', '03', '개인', '256771728', '75577723', '14181287.1', '15843818.715'], ['2022', '05', '개인', '238866649', '28185559', '14344240.1', '1457446.39'], ['2022', '06', '개인', '254486733', '15468022', '15087457.3', '838539.99'], ['2022', '07', '개인', '336383318', '10701998', '14907198', '50033.827'], ['2022', '08', '개인', '382965547', '8718677', '15555926.8', '3278812.728'], ['2022', '09', '개인', '294121752', '9220604.8', '15016541.4', '7221052.414'], ['2022', '11', '개인', '252081207', '28471902', '14485236.6', '10685943.786'], ['2022', '12', '개인', '266989892', '52230601', '14538742.5', '31655489.658'], ['2023', '04', '개인', '247142965', '38484227', '13951884.7', '4292056.162'], ['2023', '06', '개인', '259143276', '14742811', '14822130.1', '1169879.028'], ['2023', '08', '개인', '407479395', '8486915', '15402396.8', '530124.99'], ['2023', '09', '개인', '332452167', '7674573', '14941654.4', '19457189.828'], ['2023', '10', '개인', '255560826', '11273798', '14918622.9', '3049594.261'], ['2023', '11', '개인', '255362764', '23749738', '14439208.8', '13225464.736'], ['2023', '12', '개인', '271015225', '47560201', '14519931.6', '24169250.596'], ['2024', '01', '개인', '290223476', '65608930', '14119336.8', '26759601.094'], ['2024', '02', '개인', '280810330', '65184440', '14247296.7', '18696968.203'], ['2024', '03', '개인', '259332255', '58563376', '13792441.8', '13455710.256'], ['2024', '04', '개인', '256332884', '35786315', '14330249.1', '3099650.225'], ['2024', '05', '개인', '244740675', '18077028', '14158142.9', '28333197.76'], ['2024', '06', '개인', '270158916', '11903071', '14966075.6', '20226852.923'], ['2024', '07', '개인', '340000663', '8319412', '14992942.2', '2173041.617'], ['2024', '08', '개인', '463971328', '7072251', '15873544.6', '130082.263'], ['2024', '09', '개인', '409872908', '5729131', '15143321.6', '3420507.136'], ['2024', '10', '개인', '282268119', '8233421', '15297669.9', '2695491.396'], ['2024', '11', '개인', '257927956', '17418221', '14678672.5', '8836296.454'], ['2024', '12', '개인', '134828126', '42103424', '7326853.6', '1513199.277']]
[['2015' '01' '개인' '193784708' '59133720' '12819757.886' '22740838.937']
 ['2015' '02' '개인' '189974230' '56487358' '12656888.218' '18793320.213']
 ['2015' '05' '개인' '177289769' '22060892' '13086734.214' '1320895.801']
 ['2015' '06' '개인' '186073153' '12677645' '14241651.402' '294312.634']
 ['2015' '07' '개인' '165114568' '8893640' '12083879.038' '702863.645']
 ['2015' '08' '개인' '242000479' '7619018' '15164553.742' '460288.965']
 ['2015' '10' '개인' '186473958' '8924018' '14711828.766' '3167520.127']
 ['2015' '12' '개인' '203388142' '40095231' '13904162.958' '21102616.717']
 ['2016' '01' '개인' '215330620' '57641741' '13218916.436' '27186166.133']
 ['2016' '02' '개인' '216677664' '68879796' '13312113.622' '21452994.715']
 ['2016' '03' '개인' '203451798' '60019600' '13191615.499' '14070182.978']
 ['2016' '04' '개인' '202541336' '40370608' '13748935.736' '4556396.936']
 ['2016' '05' '개인' '195448592' '23077064' '13762618.524' '1166907.615']
 ['2016' '06' '개인' '205061790' '13344932' '14543461.284' '340601.066']
 ['2016' '09' '개인' '241676328' '7030657' '15233262.266' '2597269.386']
 ['2016' '10' '개인' '197827666' '10129547' '15173666.268' '2142328.405']
 ['2016' '11' '개인' '204812090' '23915383' '7215169' '10865402.481']
 ['2017' '01' '개인' '222980440' '61781772' '14077034.016' '20567265.356']
 ['2017' '02' '개인' '226181991' '73537514' '13724166.552' '17733782.246']
 ['2017' '03' '개인' '208386870' '64297007' '13598081.92' '11477962.549']
 ['2017' '05' '개인' '209894672' '25103152' '12950202.184' '19809726.81']
 ['2017' '08' '개인' '297850172' '8429188' '14291829.084' '118927.011']
 ['2017' '09' '개인' '232360099' '8981707' '13842675.562' '1279967.753']
 ['2017' '10' '개인' '202205893' '11910453' '13811362.596' '2177857.689']
 ['2017' '11' '개인' '215620132' '26041170' '13268391.686' '12290667.843']
 ['2018' '02' '개인' '243271752' '88496947' '12905042.86' '22671708.494']
 ['2018' '03' '개인' '219203768' '73426397' '12769174.532' '10924939.951']
 ['2018' '06' '개인' '222820943' '17132065' '14051336.092' '285820.628']
 ['2018' '07' '개인' '269705511' '11259835' '14333667.052' '25843523.832']
 ['2018' '11' '개인' '227294230' '31239511' '13706690.088' '10276290.855']
 ['2018' '12' '개인' '238692561' '54019855' '13732488.456' '20421845.603']
 ['2019' '01' '개인' '253600219' '80308239' '13442971.1' '21963093.848']
 ['2019' '02' '개인' '244927344' '81902188' '13495213.9' '106134923.132']
 ['2019' '03' '개인' '223736787' '65146586.443' '13167550' '13194262.09']
 ['2019' '04' '개인' '232166121' '49391508' '13753270.8' '7858587.747']
 ['2019' '06' '개인' '226119779' '15771701' '14223536.4' '331690.945']
 ['2019' '07' '개인' '257854441' '10700835' '14451345.9' '968957.161']
 ['2019' '10' '개인' '228095713' '11876816' '14804362.3' '2590192.143']
 ['2019' '11' '개인' '231283724' '24835894' '14123043.9' '14983364.884']
 ['2019' '12' '개인' '244976724' '54509050' '14184785.2' '23558262.283']
 ['2020' '02' '개인' '254879033' '76363768' '14052828.8' '20848668.612']
 ['2020' '03' '개인' '244369714' '64367515' '13841531' '14194450.151']
 ['2020' '04' '개인' '247831442' '48373693' '14618775.2' '8499792.566']
 ['2020' '08' '개인' '320723239' '10177428' '15600097.8' '286814.663']
 ['2020' '11' '개인' '247308528' '30095679' '14835013.9' '12882737.572']
 ['2020' '12' '개인' '265370372' '51095720' '15036546.3' '26512966.052']
 ['2021' '01' '개인' '287882528' '80955422' '14273105.8' '31069705.783']
 ['2021' '02' '개인' '271224712' '85581769' '13679936.9' '22238103.26']
 ['2021' '05' '개인' '241741576' '24638403' '14312460.916' '2246730.037']
 ['2021' '06' '개인' '254958704' '18898880' '15174790.6' '396903.273']
 ['2021' '07' '개인' '334733756' '9631171' '16619105.064' '5529269.058']
 ['2021' '08' '개인' '409719040' '10205066' '15737994.8' '127607.838']
 ['2021' '09' '개인' '290606638' '6602872' '15497783.9' '159066.058']
 ['2021' '10' '개인' '253845816' '13840155' '15930639.8' '4220985.501']
 ['2021' '11' '개인' '255516339' '28571168' '14975050.4' '13463697.643']
 ['2021' '12' '개인' '265314948' '54651317' '14873728.5' '25989752.285']
 ['2022' '03' '개인' '256771728' '75577723' '14181287.1' '15843818.715']
 ['2022' '05' '개인' '238866649' '28185559' '14344240.1' '1457446.39']
 ['2022' '06' '개인' '254486733' '15468022' '15087457.3' '838539.99']
 ['2022' '07' '개인' '336383318' '10701998' '14907198' '50033.827']
 ['2022' '08' '개인' '382965547' '8718677' '15555926.8' '3278812.728']
 ['2022' '09' '개인' '294121752' '9220604.8' '15016541.4' '7221052.414']
 ['2022' '11' '개인' '252081207' '28471902' '14485236.6' '10685943.786']
 ['2022' '12' '개인' '266989892' '52230601' '14538742.5' '31655489.658']
 ['2023' '04' '개인' '247142965' '38484227' '13951884.7' '4292056.162']
 ['2023' '06' '개인' '259143276' '14742811' '14822130.1' '1169879.028']
 ['2023' '08' '개인' '407479395' '8486915' '15402396.8' '530124.99']
 ['2023' '09' '개인' '332452167' '7674573' '14941654.4' '19457189.828']
 ['2023' '10' '개인' '255560826' '11273798' '14918622.9' '3049594.261']
 ['2023' '11' '개인' '255362764' '23749738' '14439208.8' '13225464.736']
 ['2023' '12' '개인' '271015225' '47560201' '14519931.6' '24169250.596']
 ['2024' '01' '개인' '290223476' '65608930' '14119336.8' '26759601.094']
 ['2024' '02' '개인' '280810330' '65184440' '14247296.7' '18696968.203']
 ['2024' '03' '개인' '259332255' '58563376' '13792441.8' '13455710.256']
 ['2024' '04' '개인' '256332884' '35786315' '14330249.1' '3099650.225']
 ['2024' '05' '개인' '244740675' '18077028' '14158142.9' '28333197.76']
 ['2024' '06' '개인' '270158916' '11903071' '14966075.6' '20226852.923']
 ['2024' '07' '개인' '340000663' '8319412' '14992942.2' '2173041.617']
 ['2024' '08' '개인' '463971328' '7072251' '15873544.6' '130082.263']
 ['2024' '09' '개인' '409872908' '5729131' '15143321.6' '3420507.136']
 ['2024' '10' '개인' '282268119' '8233421' '15297669.9' '2695491.396']
 ['2024' '11' '개인' '257927956' '17418221' '14678672.5' '8836296.454']
 ['2024' '12' '개인' '134828126' '42103424' '7326853.6' '1513199.277']]
['2015' '01' '개인' '193784708' '59133720' '12819757.886' '22740838.937'
 '2015' '02' '개인' '189974230' '56487358' '12656888.218' '18793320.213'
 '2015' '05' '개인' '177289769' '22060892' '13086734.214' '1320895.801'
 '2015' '06' '개인' '186073153' '12677645' '14241651.402' '294312.634'
 '2015' '07' '개인' '165114568' '8893640' '12083879.038' '702863.645' '2015'
 '08' '개인' '242000479' '7619018' '15164553.742' '460288.965' '2015' '10'
 '개인' '186473958' '8924018' '14711828.766' '3167520.127' '2015' '12' '개인'
 '203388142' '40095231' '13904162.958' '21102616.717' '2016' '01' '개인'
 '215330620' '57641741' '13218916.436' '27186166.133' '2016' '02' '개인'
 '216677664' '68879796' '13312113.622' '21452994.715' '2016' '03' '개인'
 '203451798' '60019600' '13191615.499' '14070182.978' '2016' '04' '개인'
 '202541336' '40370608' '13748935.736' '4556396.936' '2016' '05' '개인'
 '195448592' '23077064' '13762618.524' '1166907.615' '2016' '06' '개인'
 '205061790' '13344932' '14543461.284' '340601.066' '2016' '09' '개인'
 '241676328' '7030657' '15233262.266' '2597269.386' '2016' '10' '개인'
 '197827666' '10129547' '15173666.268' '2142328.405' '2016' '11' '개인'
 '204812090' '23915383' '7215169' '10865402.481' '2017' '01' '개인'
 '222980440' '61781772' '14077034.016' '20567265.356' '2017' '02' '개인'
 '226181991' '73537514' '13724166.552' '17733782.246' '2017' '03' '개인'
 '208386870' '64297007' '13598081.92' '11477962.549' '2017' '05' '개인'
 '209894672' '25103152' '12950202.184' '19809726.81' '2017' '08' '개인'
 '297850172' '8429188' '14291829.084' '118927.011' '2017' '09' '개인'
 '232360099' '8981707' '13842675.562' '1279967.753' '2017' '10' '개인'
 '202205893' '11910453' '13811362.596' '2177857.689' '2017' '11' '개인'
 '215620132' '26041170' '13268391.686' '12290667.843' '2018' '02' '개인'
 '243271752' '88496947' '12905042.86' '22671708.494' '2018' '03' '개인'
 '219203768' '73426397' '12769174.532' '10924939.951' '2018' '06' '개인'
 '222820943' '17132065' '14051336.092' '285820.628' '2018' '07' '개인'
 '269705511' '11259835' '14333667.052' '25843523.832' '2018' '11' '개인'
 '227294230' '31239511' '13706690.088' '10276290.855' '2018' '12' '개인'
 '238692561' '54019855' '13732488.456' '20421845.603' '2019' '01' '개인'
 '253600219' '80308239' '13442971.1' '21963093.848' '2019' '02' '개인'
 '244927344' '81902188' '13495213.9' '106134923.132' '2019' '03' '개인'
 '223736787' '65146586.443' '13167550' '13194262.09' '2019' '04' '개인'
 '232166121' '49391508' '13753270.8' '7858587.747' '2019' '06' '개인'
 '226119779' '15771701' '14223536.4' '331690.945' '2019' '07' '개인'
 '257854441' '10700835' '14451345.9' '968957.161' '2019' '10' '개인'
 '228095713' '11876816' '14804362.3' '2590192.143' '2019' '11' '개인'
 '231283724' '24835894' '14123043.9' '14983364.884' '2019' '12' '개인'
 '244976724' '54509050' '14184785.2' '23558262.283' '2020' '02' '개인'
 '254879033' '76363768' '14052828.8' '20848668.612' '2020' '03' '개인'
 '244369714' '64367515' '13841531' '14194450.151' '2020' '04' '개인'
 '247831442' '48373693' '14618775.2' '8499792.566' '2020' '08' '개인'
 '320723239' '10177428' '15600097.8' '286814.663' '2020' '11' '개인'
 '247308528' '30095679' '14835013.9' '12882737.572' '2020' '12' '개인'
 '265370372' '51095720' '15036546.3' '26512966.052' '2021' '01' '개인'
 '287882528' '80955422' '14273105.8' '31069705.783' '2021' '02' '개인'
 '271224712' '85581769' '13679936.9' '22238103.26' '2021' '05' '개인'
 '241741576' '24638403' '14312460.916' '2246730.037' '2021' '06' '개인'
 '254958704' '18898880' '15174790.6' '396903.273' '2021' '07' '개인'
 '334733756' '9631171' '16619105.064' '5529269.058' '2021' '08' '개인'
 '409719040' '10205066' '15737994.8' '127607.838' '2021' '09' '개인'
 '290606638' '6602872' '15497783.9' '159066.058' '2021' '10' '개인'
 '253845816' '13840155' '15930639.8' '4220985.501' '2021' '11' '개인'
 '255516339' '28571168' '14975050.4' '13463697.643' '2021' '12' '개인'
 '265314948' '54651317' '14873728.5' '25989752.285' '2022' '03' '개인'
 '256771728' '75577723' '14181287.1' '15843818.715' '2022' '05' '개인'
 '238866649' '28185559' '14344240.1' '1457446.39' '2022' '06' '개인'
 '254486733' '15468022' '15087457.3' '838539.99' '2022' '07' '개인'
 '336383318' '10701998' '14907198' '50033.827' '2022' '08' '개인'
 '382965547' '8718677' '15555926.8' '3278812.728' '2022' '09' '개인'
 '294121752' '9220604.8' '15016541.4' '7221052.414' '2022' '11' '개인'
 '252081207' '28471902' '14485236.6' '10685943.786' '2022' '12' '개인'
 '266989892' '52230601' '14538742.5' '31655489.658' '2023' '04' '개인'
 '247142965' '38484227' '13951884.7' '4292056.162' '2023' '06' '개인'
 '259143276' '14742811' '14822130.1' '1169879.028' '2023' '08' '개인'
 '407479395' '8486915' '15402396.8' '530124.99' '2023' '09' '개인'
 '332452167' '7674573' '14941654.4' '19457189.828' '2023' '10' '개인'
 '255560826' '11273798' '14918622.9' '3049594.261' '2023' '11' '개인'
 '255362764' '23749738' '14439208.8' '13225464.736' '2023' '12' '개인'
 '271015225' '47560201' '14519931.6' '24169250.596' '2024' '01' '개인'
 '290223476' '65608930' '14119336.8' '26759601.094' '2024' '02' '개인'
 '280810330' '65184440' '14247296.7' '18696968.203' '2024' '03' '개인'
 '259332255' '58563376' '13792441.8' '13455710.256' '2024' '04' '개인'
 '256332884' '35786315' '14330249.1' '3099650.225' '2024' '05' '개인'
 '244740675' '18077028' '14158142.9' '28333197.76' '2024' '06' '개인'
 '270158916' '11903071' '14966075.6' '20226852.923' '2024' '07' '개인'
 '340000663' '8319412' '14992942.2' '2173041.617' '2024' '08' '개인'
 '463971328' '7072251' '15873544.6' '130082.263' '2024' '09' '개인'
 '409872908' '5729131' '15143321.6' '3420507.136' '2024' '10' '개인'
 '282268119' '8233421' '15297669.9' '2695491.396' '2024' '11' '개인'
 '257927956' '17418221' '14678672.5' '8836296.454' '2024' '12' '개인'
 '134828126' '42103424' '7326853.6' '1513199.277']

In [20]:

# 계절 구분 함수
def get_season(month):
    if month in [3, 4, 5]:
        return '봄'
    elif month in [6, 7, 8]:
        return '여름'
    elif month in [9, 10, 11]:
        return '가을'
    else:
        return '겨울'

# 계절 컬럼 추가
df['season'] = df['month'].apply(get_season)

print("전처리 완료 — year, month, season 컬럼 추가됨:")
df

KeyError: 'month'

### 6-1 데이터 훑어보기

In [ ]:
import pandas as pd
import numpy as np

data = {
    'name': ['김민수', '이지영', '박준호', '최서연', '정도윤'],
    'age': [25, 30, 28, 22, 35],
    'city': ['서울', '부산', '인천', '서울', '대전'],
    'score': [90, 85, 95, 80, np.nan]
}
df = pd.DataFrame(data)

# 데이터 측정

# 모든 데이터 타입 측정

# 수치형 데이터 측정

# 범주형 데이터 측정

# 특정 열 분석

### 6-2 DataFrame 열 선택 및 **조작**

In [ ]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)

# 특정 열 선택

# DataFrame 열순서 변경

# DataFrame 열이름 변경

### 6-3 DataFrame 행 선택

In [ ]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

#DataFrame 인덱스 지정

#DataFrame 행 선택

#DataFrame 위치 기반 행 선택

#DataFrame 조건 기반 선택

### 6-4 DataFrame 정렬

In [ ]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

#DataFrame 인덱스 지정

#DataFrame 단일 열 오름차순, 내림차순 정렬

#DataFrame 복수 열 오름차순, 내림차순 정렬

#DataFrame 인덱스 기분 오른차순, 내림차순 정렬

## 6-5 실습 시나리오 - Kaggle을 활용한 데이터 수집 및 측정

- Kaggle([https://www.kaggle.com](https://www.kaggle.com)) 회원 가입
- Kaggle 접근 토큰 생성(API 키)

### Kaggle API 키 업로드

In [ ]:
from google.colab import files
files.upload()

### Kaggle API 키 사용을 위한 Colab 환경 설정

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

### Kaggle 데이터셋 다운로드

In [ ]:
!kaggle competitions download –c store-sales-time-series-forecasting

!unzip store-sales-time-series-forecasting.zip

### Kaggle 데이터셋 DataFrame 로드 및 살펴보기

In [ ]:
import pandas as pd

# Grocery Sales 데이터 DataFrame 로드

# 판매 데이터 살펴보기

### Kaggle 데이터셋 측정

In [ ]:
# 판매 데이터 기본 통계량

# 매장 데이터 기본 정보

# 원유 가격 데이터 기본 정보